{
 "title": "111New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "child",
    "query": {
     "query": "label_values(http_out_duration_second_bucket{},child)"
    }
   },
   {
    "name": "le",
    "label": "返回时间上限",
    "query": {
     "query": "label_values(http_out_duration_second_bucket{},le)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "请求时间",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(http_out_duration_second_sum{child=~\"$child\"}[5m]))  by (child,code)\r\n/\r\nsum(irate(http_out_duration_second_count{child=~\"$child\"}[5m])) by (child,code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求速率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(http_out_duration_second_count{child=~\"$child\"}[5m]) * 15",
     "legendFormat": "{child=\"{{ child }}\",code=\"{{ code }}\"}"
    }
   ]
  },
  {
   "title": "接口返回监测图表",
   "type": "table",
   "description": "采样结果被量化为一个 0 到 1之间的数值即 “Apdex 指数”，0 代表没有满意用户，1则代表所有用户都满意。",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_out_duration_second_bucket{child=~\"$child\"}[5m])) by (child,code,le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_out_duration_second_bucket{child=~\"$child\"}[5m])) by (child,code,le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_out_duration_second_bucket{child=~\"$child\"}[5m])) by (child,code,le))"
    },
    {
     "expr": "sum(rate(http_out_duration_second_sum{child=~\"$child\"}[5m]))  by (child,code)\r\n/\r\nsum(rate(http_out_duration_second_count{child=~\"$child\"}[5m])) by (child,code)"
    },
    {
     "expr": "sum(rate(http_out_duration_second_bucket{child=~\"$child\",le=~\"$le\"}[5m]))by(child,code)/sum(rate(http_out_duration_second_count{child=~\"$child\"}[5m]))by(child,code)"
    },
    {
     "expr": "(sum(rate(http_out_duration_second_bucket{child=~\"$child\",le=~\"$le\"}[5m])) by (child) + sum(rate(http_out_duration_second_bucket{child=~\"$child\",le=\"4.0\"}[5m])) by (child)) / 2 / sum(rate(http_out_duration_second_count{child=~\"$child\"}[5m])) by (child)"
    }
   ]
  }
 ]
}