version: '3.7'
services:
  tms-gah-broker:
    build:
      context: ../
      dockerfile: Dockerfile
    image: tms/gah-broker:latest
    container_name: tms-gah-broker
    ports:
      - '8080:8080'
    environment:
      - TGAH_BUCKET_ENABLE=no
      - TGAH_API_DEF_PATH=../example/apis # API定义文件存放位置
      - TGAH_FLOW_DEF_PATH=../example/flows # FLOW定义文件存放位置
    volumes:
      - ../example:/home/tms-gah/broker/conf
      - ../schema:/home/tms-gah/schema
