version: '3.7'
services:
  tms-gah-broker:
    build:
      context: ../
      dockerfile: Dockerfile
    image: tms/gah-broker:latest
    container_name: tms-gah-broker
    # ports:
    #   - '8080:8080'
    # environment:
    # volumes:
    #   - ../example:/home/tms-gah/example
    command: ['/home/tms-gah/broker/startup.sh']
